authors:
  zakeri:
    name: Morteza Zakeri
    description: Creator
    avatar: https://avatars.githubusercontent.com/m-zakeri
    url: https://github.com/m-zakeri
  aghajari:
    name: AmirHossein Aghajari
    description: AUT student in Fall 2024
    avatar: https://avatars.githubusercontent.com/aghajari
    url: https://github.com/aghajari
